### ISSUE TITLE
[FEATURE] 아티스트 그룹 CRUD

### ISSUE THREAD

**Issue by gaeun7** [FanTree-House/FanTree-Back#8]
## Description
아티스트 그룹 CRUD

## To-do
- [ ] 아티스트 그룹 생성
- [ ] 아티스트 그룹 조회
- [ ] 아티스트 그룹 수정
- [ ] 아티스트 그룹 삭제

## 작업 내용
아티스트 그룹을 생성
